# Generated by Django 2.1.4 on 2018-12-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='forma_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de crédito', 'Cartão de crédito'), ('Cartão de débito', 'Cartão de débito'), ('Cartão de crediário', 'Cartão de crediário'), ('Cheque', 'Cheque')], max_length=20, verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='vencimento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vencimento'),
        ),
    ]
