# Generated by Django 2.1.4 on 2018-12-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_auto_20181220_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='vencimento',
            field=models.DateTimeField(verbose_name='Vencimento'),
        ),
    ]
