# Generated by Django 2.1.4 on 2018-12-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_auto_20181220_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='vencimento',
            field=models.DateField(verbose_name='Vencimento'),
        ),
    ]
