# Generated by Django 2.1.4 on 2018-12-21 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0011_auto_20181220_2223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Despesa',
        ),
    ]
