# Generated by Django 2.1.4 on 2018-12-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('despesas', '0012_delete_despesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(verbose_name='Data da criação')),
                ('tipo', models.CharField(choices=[('Alimentação', 'Alimentação'), ('Educação', 'Educação'), ('Lazer', 'Lazer'), ('Remédio', 'Remédio'), ('Roupa', 'Roupa'), ('Transporte', 'Transporte'), ('Outro', 'Outro')], max_length=15, verbose_name='Tipo de Despesa')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('vencimento', models.DateTimeField(verbose_name='Vencimento')),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de crédito', 'Cartão de crédito'), ('Cartão de débito', 'Cartão de débito'), ('Cartão de crediário', 'Cartão de crediário'), ('Cheque', 'Cheque')], max_length=20, verbose_name='Forma de pagamento')),
                ('pago', models.BooleanField()),
            ],
            options={
                'ordering': ('vencimento', 'forma_pagamento'),
            },
        ),
    ]
